name: sqljocky
version: 0.1.1
description: >
  A MySQL connector
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/sqljocky
dependencies:
  options_file: "0.9.3"
  unittest: any
  logging: any
